"""
Due Diligence MVP - Phase 1 Report Generator

Generates professional HTML reports with:
- Property title details
- Location map (SVG)
- Disclaimers and attribution
"""

import json
from datetime import datetime
from pathlib import Path
import sys

sys.stdout.reconfigure(encoding='utf-8')

def generate_html_report(result_data, output_path=None, include_interactive_map=True):
    """
    Generate HTML report from query result
    
    Args:
        result_data: Dictionary with address and title info
        output_path: Path to save HTML file (optional)
        include_interactive_map: If True, use Leaflet; if False, use static SVG
    
    Returns:
        HTML string and path to saved file
    """
    
    address = result_data.get('address', {})
    title = result_data.get('title', {})
    
    if not title:
        return _generate_no_result_report(address)
    
    # Extract data
    full_address = f"{address.get('full_address', 'Address Not Found')}"
    coords = f"{address.get('latitude', 0):.6f}, {address.get('longitude', 0):.6f}"
    
    title_no = title.get('title_no', 'Unknown')
    status = title.get('status', 'Unknown')
    title_type = title.get('type', 'Unknown')
    estate = title.get('estate', 'Unknown')
    guarantee = title.get('guarantee_status', 'Unknown')
    district = title.get('land_district', 'Unknown')
    issue_date = title.get('issue_date', 'Unknown')
    owners = title.get('number_owners', 'Unknown')
    
    # Parse estate for area
    area = _extract_area(estate)
    
    # Generate map SVG
    map_svg = _generate_location_map(
        lat=address.get('latitude'),
        lon=address.get('longitude'),
        title_no=title_no,
        geometry=title.get('geometry')
    )
    
    # Build HTML
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Property Due Diligence Report - {title_no}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}
        .container {{ background: white; padding: 40px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        .header {{ border-bottom: 3px solid #007A4D; padding-bottom: 20px; margin-bottom: 30px; }}
        .header h1 {{ color: #007A4D; font-size: 28px; margin-bottom: 5px; }}
        .header .subtitle {{ color: #666; font-size: 14px; }}
        .section {{ margin-bottom: 30px; }}
        .section h2 {{ color: #2D2D2D; font-size: 20px; border-left: 4px solid #FFB81C; padding-left: 15px; margin-bottom: 15px; }}
        .info-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin-bottom: 20px; }}
        .info-item {{ background: #f9f9f9; padding: 15px; border-radius: 5px; border-left: 3px solid #007A4D; }}
        .info-item label {{ font-weight: 600; color: #555; font-size: 12px; text-transform: uppercase; display: block; margin-bottom: 5px; }}
        .info-item value {{ font-size: 16px; color: #333; font-weight: 500; }}
        .map-container {{ text-align: center; margin: 20px 0; }}
        .map-container svg {{ max-width: 100%; height: auto; border: 2px solid #ddd; border-radius: 5px; }}
        .disclaimer {{ background: #fff3cd; border: 1px solid #ffc107; padding: 15px; border-radius: 5px; font-size: 12px; color: #856404; margin-top: 30px; }}
        .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; text-align: center; }}
        .badge {{ display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; text-transform: uppercase; }}
        .badge-live {{ background: #d4edda; color: #155724; }}
        .badge-cancelled {{ background: #f8d7da; color: #721c24; }}
        .badge-freehold {{ background: #cce5ff; color: #004085; }}
        .badge-crosslease {{ background: #e2e3e5; color: #383d41; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🏠 Property Due Diligence Report</h1>
            <div class="subtitle">Generated by AI Driven | {datetime.now().strftime('%Y-%m-%d %H:%M')}</div>
        </div>
        
        <div class="section">
            <h2>Property Address</h2>
            <div class="info-item">
                <value style="font-size: 18px;">{full_address}</value>
                <div style="margin-top: 8px; font-size: 13px; color: #666;">
                    Coordinates: {coords}
                </div>
            </div>
        </div>
        
        <div class="section">
            <h2>Title Details</h2>
            <div class="info-grid">
                <div class="info-item">
                    <label>Title Number</label>
                    <value style="font-size: 20px; color: #007A4D; font-weight: 700;">{title_no}</value>
                </div>
                <div class="info-item">
                    <label>Status</label>
                    <value><span class="badge badge-live">{status}</span></value>
                </div>
                <div class="info-item">
                    <label>Land District</label>
                    <value>{district}</value>
                </div>
                <div class="info-item">
                    <label>Issue Date</label>
                    <value>{issue_date[:10] if issue_date and 'T' in str(issue_date) else issue_date}</value>
                </div>
            </div>
            
            <div class="info-grid">
                <div class="info-item">
                    <label>Estate Type</label>
                    <value>{title_type}</value>
                </div>
                <div class="info-item">
                    <label>Guarantee</label>
                    <value>{guarantee}</value>
                </div>
                <div class="info-item">
                    <label>Area</label>
                    <value>{area if area else 'Not specified'}</value>
                </div>
                <div class="info-item">
                    <label>Number of Owners</label>
                    <value>{owners}</value>
                </div>
            </div>
            
            <div class="info-item" style="border-left-color: #FFB81C;">
                <label>Estate Description</label>
                <value style="display: block; margin-top: 8px;">{estate}</value>
            </div>
        </div>
        
        <div class="section">
            <h2>Location Map</h2>
            {map_svg}
        </div>
        
        <div class="disclaimer">
            <strong>⚠️ Disclaimer:</strong> This report is generated from LINZ Data Service information and is provided for due diligence purposes only. 
            It does not constitute legal advice or a guarantee of title accuracy. 
            Always verify critical information with a qualified solicitor or licensed surveyor before making property decisions.
            <br><br>
            <strong>Data Source:</strong> Contains LINZ data © Crown copyright licensed under Creative Commons Attribution 4.0 International
        </div>
        
        <div class="footer">
            Report generated by AI Driven | www.aidriven.biz<br>
            For inquiries: gerhard@aidriven.biz
        </div>
    </div>
</body>
</html>
"""
    
    # Save file
    if output_path is None:
        output_dir = Path(__file__).parent / 'reports'
        output_dir.mkdir(exist_ok=True)
        timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
        safe_title = title_no.replace('/', '-')
        output_path = output_dir / f'report-{safe_title}-{timestamp}.html'
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)
    
    print(f"✅ Report saved: {output_path}")
    
    return html, output_path

def _extract_area(estate_description):
    """Extract area in m² from estate description"""
    import re
    if not estate_description:
        return None
    
    # Look for pattern like "803 m2" or "1,315 m2"
    match = re.search(r'(\d[\d,]*)\s*m2', estate_description, re.IGNORECASE)
    if match:
        area_str = match.group(1).replace(',', '')
        return f"{int(float(area_str)):,} m²"
    
    return None

def _generate_location_map(lat, lon, title_no, geometry=None, include_interactive=True):
    """
    Generate location map
    
    Args:
        lat, lon: Coordinates
        title_no: Title number for labeling
        geometry: GeoJSON geometry (for drawing boundary)
        include_interactive: If True, return Leaflet HTML; if False, return static SVG
    """
    if not lat or not lon:
        if include_interactive:
            return '<div style="padding: 40px; background: #f5f5f5; text-align: center; color: #999;">Map data unavailable</div>'
        else:
            return '<div style="padding: 40px; background: #f5f5f5; text-align: center; color: #999;">Map data unavailable</div>'
    
    if include_interactive:
        # Generate interactive Leaflet map
        return _generate_leaflet_map(lat, lon, title_no, geometry)
    else:
        # Generate static SVG for PDF
        return _generate_static_svg(lat, lon, title_no, geometry)
    
def _generate_leaflet_map(lat, lon, title_no, geometry=None):
    """Generate interactive Leaflet map HTML"""
    
    # Prepare geometry for GeoJSON if available
    geojson_data = 'null'
    if geometry and isinstance(geometry, dict):
        import json
        geojson_data = json.dumps(geometry)
    
    html = f"""
    <div id="map" style="height: 450px; width: 100%; border-radius: 8px; border: 2px solid #ddd;"></div>
    <div style="margin-top: 10px; font-size: 12px; color: #666; text-align: center;">
        🗺️ Interactive map - scroll to zoom, drag to pan | Data: © OpenStreetMap contributors
    </div>
    
    <!-- Leaflet CSS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    
    <!-- Leaflet JS -->
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    
    <script>
        // Initialize map centered on property
        var map = L.map('map').setView([{lat}, {lon}], 16);
        
        // Add OpenStreetMap tiles
        L.tileLayer('https://{{s}}.tile.openstreetmap.org/{{z}}/{{x}}/{{y}}.png', {{
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            maxZoom: 19
        }}).addTo(map);
        
        // Add address point marker
        var marker = L.marker([{lat}, {lon}]).addTo(map);
        marker.bindPopup('<b>{title_no}</b><br>Address Location').openPopup();
        
        // Add property boundary if geometry available
        var boundaryData = {geojson_data};
        if (boundaryData && boundaryData.type) {{
            var geojsonLayer = L.geoJSON(boundaryData, {{
                style: function(feature) {{
                    return {{
                        color: '#007A4D',
                        weight: 3,
                        opacity: 0.8,
                        fillOpacity: 0.2,
                        fillColor: '#FFB81C'
                    }};
                }}
            }}).addTo(map);
            
            // Fit map to show both boundary and marker
            var group = new L.featureGroup([marker, geojsonLayer]);
            map.fitBounds(group.getBounds(), {{padding: [50, 50]}});
        }}
        
        // Add scale control
        L.control.scale({{metric: true, imperial: false}}).addTo(map);
    </script>
    """
    
    return html

def _generate_static_svg(lat, lon, title_no, geometry=None):
    """
    Generate simple SVG location map for PDF
    Shows property centroid and address point
    """
    if not lat or not lon:
        return '<div style="padding: 40px; background: #f5f5f5; text-align: center; color: #999;">Map data unavailable</div>'
    
    # Convert lat/lon to SVG coordinates (simple equirectangular projection)
    # Center map on the property
    center_lon = lon
    center_lat = lat
    
    # Scale: approximately 1 degree = 111km
    # Show roughly 500m x 500m area
    span_degrees = 0.005  # ~555 meters
    
    min_lon = center_lon - span_degrees
    max_lon = center_lon + span_degrees
    min_lat = center_lat - span_degrees
    max_lat = center_lat + span_degrees
    
    def to_svg_x(lon_val):
        return ((lon_val - min_lon) / (max_lon - min_lon)) * svg_width
    
    def to_svg_y(lat_val):
        return svg_height - ((lat_val - min_lat) / (max_lat - min_lat)) * svg_height
    
    # Calculate address point position
    addr_x = to_svg_x(lon)
    addr_y = to_svg_y(lat)
    
    svg = f"""<svg width="{svg_width}" height="{svg_height}" viewBox="0 0 {svg_width} {svg_height}" xmlns="http://www.w3.org/2000/svg">
        <!-- Background -->
        <rect width="{svg_width}" height="{svg_height}" fill="#f0f4f8"/>
        
        <!-- Grid lines -->
        <g stroke="#d0d8e0" stroke-width="1" opacity="0.5">
            <line x1="{svg_width*0.25}" y1="0" x2="{svg_width*0.25}" y2="{svg_height}"/>
            <line x1="{svg_width*0.5}" y1="0" x2="{svg_width*0.5}" y2="{svg_height}"/>
            <line x1="{svg_width*0.75}" y1="0" x2="{svg_width*0.75}" y2="{svg_height}"/>
            <line x1="0" y1="{svg_height*0.25}" x2="{svg_width}" y2="{svg_height*0.25}"/>
            <line x1="0" y1="{svg_height*0.5}" x2="{svg_width}" y2="{svg_height*0.5}"/>
            <line x1="0" y1="{svg_height*0.75}" x2="{svg_width}" y2="{svg_height*0.75}"/>
        </g>
        
        <!-- Property boundary placeholder (will be real polygon in Phase 2) -->
        <ellipse cx="{addr_x}" cy="{addr_y}" rx="60" ry="40" fill="none" stroke="#007A4D" stroke-width="2" stroke-dasharray="5,5" opacity="0.6"/>
        <text x="{addr_x}" y="{addr_y - 50}" text-anchor="middle" font-size="11" fill="#007A4D" font-weight="600">{title_no}</text>
        
        <!-- Address point marker -->
        <circle cx="{addr_x}" cy="{addr_y}" r="8" fill="#FFB81C" stroke="#2D2D2D" stroke-width="2"/>
        <circle cx="{addr_x}" cy="{addr_y}" r="3" fill="#2D2D2D"/>
        
        <!-- North arrow -->
        <g transform="translate({svg_width - 40}, 40)">
            <polygon points="0,-15 5,5 0,0 -5,5" fill="#2D2D2D"/>
            <text x="0" y="-20" text-anchor="middle" font-size="10" font-weight="bold" fill="#2D2D2D">N</text>
        </g>
        
        <!-- Scale bar (approx 100m) -->
        <g transform="translate(20, {svg_height - 30})">
            <line x1="0" y1="0" x2="90" y2="0" stroke="#2D2D2D" stroke-width="2"/>
            <line x1="0" y1="-5" x2="0" y2="5" stroke="#2D2D2D" stroke-width="2"/>
            <line x1="90" y1="-5" x2="90" y2="5" stroke="#2D2D2D" stroke-width="2"/>
            <text x="45" y="15" text-anchor="middle" font-size="10" fill="#2D2D2D">~100m</text>
        </g>
        
        <!-- Coordinates -->
        <text x="{svg_width/2}" y="{svg_height - 10}" text-anchor="middle" font-size="9" fill="#666">
            {lat:.6f}, {lon:.6f}
        </text>
    </svg>"""
    
    return svg

def _generate_no_result_report(address):
    """Generate report when no title found"""
    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>No Title Found</title>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; }}
        .warning {{ background: #fff3cd; border: 2px solid #ffc107; padding: 20px; border-radius: 5px; }}
        h1 {{ color: #856404; }}
    </style>
</head>
<body>
    <div class="warning">
        <h1>⚠️ No Property Title Found</h1>
        <p>Could not find a property title at the specified address:</p>
        <p><strong>{address.get('full_address', 'Unknown address')}</strong></p>
        <p>This may indicate:</p>
        <ul>
            <li>Vacant land without a separate title</li>
            <li>New subdivision (titles not yet issued)</li>
            <li>Address point falls between properties</li>
            <li>Data error in LINZ records</li>
        </ul>
        <p>Recommend manual verification with LINZ Data Service.</p>
    </div>
</body>
</html>"""
    
    output_dir = Path(__file__).parent / 'reports'
    output_dir.mkdir(exist_ok=True)
    output_path = output_dir / f'report-no-result-{datetime.now().strftime("%Y%m%d-%H%M%S")}.html'
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)
    
    return html, output_path

if __name__ == '__main__':
    # Test with our sample data
    test_result = {
        'address': {
            'full_address': '31 Douglas McLean Avenue, Marewa, Napier',
            'latitude': -39.500580,
            'longitude': 176.904059
        },
        'title': {
            'title_no': 'HBE2/765',
            'status': 'LIVE',
            'type': 'Freehold',
            'estate': 'Fee Simple, 1/1, Lot 88 Deposited Plan 8162, 803 m2',
            'guarantee_status': 'Guarantee',
            'land_district': 'Hawkes Bay',
            'issue_date': '1972-11-22T00:00:00Z',
            'number_owners': 2,
            'geometry': None  # Will add in Phase 2
        }
    }
    
    html, path = generate_html_report(test_result)
    print(f"\nTest report generated: {path}")
    print("Open in browser to preview")
